# Local Development Docker Compose
# Usage:
#   First time:  docker compose -f compose.local.yaml up --build
#   Subsequent:  docker compose -f compose.local.yaml up -d
#
# This will automatically:
#   - Set up databases (metadata + MST data)
#   - Create admin and viewer users
#   - Import all dashboards, datasets, and saved queries
#   - Configure database connections

x-superset-depends-on: &superset-depends-on
  - metadata_db
  - redis
  - database

x-superset-env: &superset-env
  SUPERSET_USER: admin
  SUPERSET_PASSWORD: Giga@Mst2026!
  SUPERSET_VIEWER_USER: mst_viewer
  SUPERSET_VIEWER_PASSWORD: MstViewer2026!
  SUPERSET_META_USER: superset
  SUPERSET_META_PASS: superset
  SUPERSET_META_HOST: metadata_db
  SUPERSET_META_PORT: "5432"
  SUPERSET_SECRET_KEY: local-dev-secret-key-change-in-production
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: mst

services:
  redis:
    image: redis:latest
    container_name: superset_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  metadata_db:
    image: postgres:16.6
    container_name: superset_metadata
    restart: unless-stopped
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    ports:
      - "5433:5432"
    volumes:
      - metadata_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superset"]
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: mst_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mst
    ports:
      - "5434:5432"
    volumes:
      - mst_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # One-time initialization container
  superset_init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superset_init
    environment:
      <<: *superset-env
    command: ["/docker/local-init.sh"]
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      metadata_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      database:
        condition: service_healthy

  superset:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superset_app
    restart: always
    environment:
      <<: *superset-env
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      superset_init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8088/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superset_celery_worker
    restart: unless-stopped
    environment:
      <<: *superset-env
      SE_AVOID_SELENIUM_MANAGER: "1"
      SE_DRIVER_PATH: /usr/bin/geckodriver
    command: ["/docker/superset-celery.sh", "worker"]
    volumes:
      - superset_home:/app/superset_home
    user: superset
    depends_on:
      superset_init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superset_celery_beat
    restart: unless-stopped
    environment:
      <<: *superset-env
      SE_AVOID_SELENIUM_MANAGER: "1"
      SE_DRIVER_PATH: /usr/bin/geckodriver
    command: ["/docker/superset-celery.sh", "beat"]
    volumes:
      - superset_home:/app/superset_home
    user: superset
    depends_on:
      superset_init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'celery beat' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  metadata_pgdata:
  redis_data:
  mst_pgdata:
  superset_home:
